application: bitcoinbeacon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/js
  static_dir: static/js

- url: /static/css
  static_dir: static/css

- url: /.*
  script: bitcoinbeacon.application  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
